apps/document/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required


from apps.document.views import Document_create, Detalle_doc, Create_value, Active_off, Documento_list, Documento_edit, Edit_value, \
    DocumentoCreate

urlpatterns = [
    url(r'^$', login_required(Document_create), name='document_form'),
    url(r'^nuevo$', login_required(Document_create), name='document_form'),
    url(r'^nuevo/(?P<value>\w+)$', login_required(Create_value), name='create_value'),
    url(r'^editar/(?P<value>\w+)/(?P<id_value>\d+)$', login_required(Edit_value), name='edit_value'),
    url(r'^active_off/(?P<value>\w+)/(?P<id_value>\d+)$', login_required(Active_off), name='active_off'),
    url(r'^list/$', login_required(Documento_list), name="documento_list"),
    url(r'^detalle/(?P<id_docum>\d+)$',login_required(Detalle_doc), name="documento_detalle"),
    url(r'^editar/(?P<id_documento>\d+)$',login_required(Documento_edit), name="documento_edit"),
    ]

apps/ticket/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.ticket.views import index, ticket_view, ticket_detalle, Cambiar_estado, \
    TicketList, TicketCreate, TicketUpdate, TicketDelete, TemaCreate, EstadosView
from apps.ticket.models import Ticket 

urlpatterns = [
    url(r'^$', login_required(EstadosView), name='ticket_home'),
    url(r'^nuevo$', login_required(ticket_view), name='ticket_form'),
    url(r'^listar/$', login_required(TicketList.as_view()), name='ticket_list'),
    url(r'^listar/abiertos$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =0))), name='ticket_list_abierto'),
    url(r'^listar/cerrados$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =1))), name='ticket_list_cerrado'),
    url(r'^listar/pendientes$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =2))), name='ticket_list_pendiente'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(TicketUpdate.as_view()), name='ticket_edit'),
    url(r'^estado/(?P<id_ticket>\d+)/(?P<id_estado>\d+)/$', login_required(Cambiar_estado), name='estado_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(TicketDelete.as_view()), name='ticket_delete'),
   url(r'^nuevo/(?P<value>\w+)', login_required(TemaCreate), name='nuevo_form'),
    url(r'^estados$', login_required(EstadosView), name='ticket_estados'),
    url(r'^detalle/(?P<id_ticket>\d+)/$', login_required(ticket_detalle), name='ticket_detalle'),
    #url(r'^nuevo$', ticket_view, name='ticket_form'),
]

apps/usuarios/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import Cuenta_edit,\
    RegistroUsuario, ListUsuario, ModificarUsuario, EliminarUsuario, TecnicoCreate

urlpatterns = [
 #   url(r'^$', index, name='ticket'),
    url(r'^$', login_required(ListUsuario.as_view()), name='usuario_list'),
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name='registrar'),
    url(r'^listar$', login_required(ListUsuario.as_view()), name='usuario_list'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(ModificarUsuario.as_view()), name='modif_usuario'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()), name='elim_usuario'),
    url(r'^cuenta$', login_required(Cuenta_edit), name='Cuenta_edit'),
    url(r'^nuevo/tecnico', login_required(TecnicoCreate.as_view()), name='tecnico_form'),
]

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf import settings
from django.conf.urls.static import static
#from apps.home.views import home
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO: mejorar orden en urls
urlpatterns += [
    url(r'^', include('apps.document.urls', namespace='document')),
    url(r'^archivos/', include('apps.archivos.urls', namespace='archivos')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^accounts/login/', login, {'template_name':'registration/login.html'}, name='login'),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuario')),
    url(r'^documentos/', include('apps.document.urls', namespace='document')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Colina Educa">
    <meta name="author" content="Octavio Cubillos">

	<title> Colina Educa - {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="/media/img/favicon.png">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/timeline.css' %}" rel="stylesheet">
    <link href="{% static 'css/startmin.css' %}" rel="stylesheet">
    <link href="{% static 'css/morris.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
{% block head %}
{% endblock %}
</head>
{% block body %}
<body>
<div id="wrapper">

	{% block header %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="navbar-header">

        </div>
        <ul class="nav navbar-nav navbar-left navbar-top-links" style="font-size: 15pt">
                    <li><a href="{{request.META.HTTP_REFERER}}" type="button" ><i class="fa fa-chevron-circle-left fa-fw" aria-hidden="true"></i> Atras</a></li>
                    <li><a href="{% url 'document:document_form' %}" type="button" ><i class="fa fa-home fa-fw" aria-hidden="true"></i></a></li>
                    <li><a href="" type="button" onClick="history.go(0)" ><i class="fa fa-refresh fa-fw" aria-hidden="true"></i></a></li>
                </ul>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>


        {% if user.is_authenticated %}
        <ul class="nav navbar-right navbar-top-links">

            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i> {% block username %} {{ user.get_username }} {% endblock %} <b class="caret"></b>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{%  url 'usuario:Cuenta_edit' %}"><i class="fa fa-gear fa-fw"></i> Conf. cuenta</a></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out fa-fw"></i> Salir</a>
                    </li>
                </ul>
            </li>
        </ul>
        {% else %}


        {% endif %}
        <!-- Sidebar -->
        <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                           <li class="sidebar-search">
                                <div class="input-group custom-search-form">

                                    <a href="{% url 'document:document_form' %}">&nbsp;&nbsp;<img src="/media/img/logo_colinaeduca.png" alt="logo" width="80%" height="auto"></a>
                                </div>
                            </li>
                        <!--    <li><a href="{% url 'document:document_form'  %}"><i class="fa fa-file-text fa-fw"></i> Inicio</a></li> -->

                            <li>
                            <a href="#" class=""><i class="fa fa-file-text fa-fw"></i> Documentos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li><a href="{% url 'document:document_form' %}" class=""><i class="fa fa-file fa-fw"></i> Nuevo</a></li>
                                <li><a href="{% url 'document:documento_list' %}" class=""><i class="fa fa-list-alt fa-fw"></i> Listado</a></li>
                            </ul>
                            </li>
                            <li>
                                <a href="#" class=""><i class="fa fa-list-alt fa-fw"></i> Tickets <span class="fa fa-code fa-fw" style="color: red"></span> desarrollo <span class="fa fa-code fa-fw" style="color: red"></span><span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li><a href="{% url 'ticket:ticket_estados' %}" class=""><i class="fa fa-check-square-o fa-fw"></i> Estados</a></li>
                                    <li><a href="{% url 'ticket:ticket_form' %}" class=""><i class="fa fa-file fa-fw"></i> Nuevo</a></li>
                                    <li><a href="{% url 'ticket:ticket_list' %}" class=""><i class="fa  fa-list-ol fa-fw"></i> Listados</a></li>
                                </ul>
                            </li>
                            <li>
                                <a href="#" class=""><i class="fa fa-user fa-fw"></i> Usuarios<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li><a href="{% url 'usuario:usuario_list' %}" class=""><i class="fa fa-users fa-fw"></i> Listado</a></li>
                                    <li><a href="{% url 'usuario:registrar' %}" class=""><i class="fa fa-user-plus fa-fw"></i> Registrar</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
    </nav>
	{% endblock %}

    <div id="page-wrapper">
        <div class="container-fluid page-header">

    {% block content %}
        {% endblock %}

{% block footer %}

    {% endblock %}
        </div>
    </div>


</div>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/printThis.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/metisMenu.min.js' %}"></script>
<script src="{% static 'js/startmin.js' %}"></script>
<script src="{% static 'js/dataTables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables/dataTables.bootstrap.min.js' %}"></script>
<!--
<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
</script>
-->
</body>
{% endblock %}
</html>