apps/ticket/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.ticket.views import index, ticket_view, ticket_detalle, Cambiar_estado, \
    TicketList, TicketCreate, TicketUpdate, TicketDelete, TemaCreate, EstadosView
from apps.ticket.models import Ticket 

urlpatterns = [
    url(r'^$', login_required(EstadosView), name='ticket_home'),
    url(r'^nuevo$', login_required(ticket_view), name='ticket_form'),
    url(r'^listar/$', login_required(TicketList.as_view()), name='ticket_list'),
    url(r'^listar/abiertos$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =0))), name='ticket_list_abierto'),
    url(r'^listar/cerrados$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =1))), name='ticket_list_cerrado'),
    url(r'^listar/pendientes$', login_required(TicketList.as_view(queryset=Ticket.objects.filter(estado_id =2))), name='ticket_list_pendiente'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(TicketUpdate.as_view()), name='ticket_edit'),
    url(r'^estado/(?P<id_ticket>\d+)/(?P<id_estado>\d+)/$', login_required(Cambiar_estado), name='estado_edit'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(TicketDelete.as_view()), name='ticket_delete'),
   url(r'^nuevo/(?P<value>\w+)', login_required(TemaCreate), name='nuevo_form'),
    url(r'^estados$', login_required(EstadosView), name='ticket_estados'),
    url(r'^detalle/(?P<id_ticket>\d+)/$', login_required(ticket_detalle), name='ticket_detalle'),
    #url(r'^nuevo$', ticket_view, name='ticket_form'),
]

apps/usuarios/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.usuarios.views import Cuenta_edit,\
    RegistroUsuario, ListUsuario, ModificarUsuario, EliminarUsuario, TecnicoCreate

urlpatterns = [
 #   url(r'^$', index, name='ticket'),
    url(r'^$', login_required(ListUsuario.as_view()), name='usuario_list'),
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name='registrar'),
    url(r'^listar$', login_required(ListUsuario.as_view()), name='usuario_list'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(ModificarUsuario.as_view()), name='modif_usuario'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(EliminarUsuario.as_view()), name='elim_usuario'),
    url(r'^cuenta$', login_required(Cuenta_edit), name='Cuenta_edit'),
    url(r'^nuevo/tecnico', login_required(TecnicoCreate.as_view()), name='tecnico_form'),
]

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf import settings
from django.conf.urls.static import static
#from apps.home.views import home
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO: mejorar orden en urls
urlpatterns += [
    url(r'^', include('apps.document.urls', namespace='document')),
    url(r'^archivos/', include('apps.archivos.urls', namespace='archivos')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^accounts/login/', login, {'template_name':'registration/login.html'}, name='login'),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuario')),
    url(r'^documentos/', include('apps.document.urls', namespace='document')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/ticket/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.usuarios.models import Tecnico
# Create your models here.

class Estado(models.Model):
	titulo = models.CharField(max_length=50)
	def __str__(self):
		return '{}'.format(self.titulo)


class Establecimiento(models.Model):
	titulo = models.CharField(max_length=50)
	def __str__(self):
		return '{}'.format(self.titulo)

class Tema(models.Model):
	titulo = models.CharField(max_length=60)
	def __str__(self):
		return '{}'.format(self.titulo)

class Ticket(models.Model):
	usuario = models.ForeignKey(User, null=False, blank=True, on_delete=models.CASCADE)
	tema = models.ForeignKey(Tema, null=False, blank=True, on_delete=models.CASCADE)
	establecimiento = models.ForeignKey(Establecimiento, null=True, blank=True, on_delete=models.CASCADE)
	nom_contacto = models.CharField(max_length=50)
	ape_contacto = models.CharField(max_length=50)
	correo_contacto = models.EmailField()
	fijo_contacto = models.IntegerField()
	celu_contacto = models.IntegerField( null=True)
	resum_problema = models.CharField(max_length=100)
	asignado = models.ForeignKey(Tecnico, null=False, blank=True, on_delete=models.CASCADE)
	detall_problema = models.TextField()
	fecha_creacion = models.DateTimeField(auto_now_add=True)
	fecha_modificacion = models.DateTimeField(auto_now=True)
	estado =  models.ForeignKey(Estado, null=False, blank=True, on_delete=models.CASCADE)
	def __str__(self):
		return '{}'.format(self.resum_problema)

class Respuestas(models.Model):
	usuario = models.TextField()
	asunto = models.CharField(max_length=50, null=False)
	mensaje = models.TextField(null=False)
	updated_at = models.DateTimeField(auto_now=True)
	created_at = models.DateTimeField(auto_now_add=True)
	ticket = models.IntegerField(null=True)

apps/ticket/forms.py
from django import forms

from apps.ticket.models import Ticket, Establecimiento, Tema, Respuestas

class TicketForm(forms.ModelForm):

	class Meta:
		model=Ticket
		fields=[
			'tema',
			'establecimiento',
			'nom_contacto',
			'ape_contacto',
			'correo_contacto',
			'fijo_contacto',
			'celu_contacto',
			'resum_problema',
			'asignado',
			'detall_problema',
			'estado',
		]
		labels={
			'tema':'Tema',
			'establecimiento':'Establecimiento',
			'nom_contacto':'Nom_contacto',
			'ape_contacto':'Ape_contacto',
			'correo_contacto':'Correo_contacto',
			'fijo_contacto':'Fijo_contacto',
			'celu_contacto':'Celu_contacto',
			'resum_problema':'Resum_problema',
			'asignado':'Asignado',
			'detall_problema':'Detall_problema',
			'estado':'Estado',
		}
		widgets={
			'tema': forms.Select(attrs={'class':'form-control'}),
			'establecimiento': forms.Select(attrs={'class':'form-control' }),
			'nom_contacto': forms.TextInput(attrs={'class':'form-control'}),
			'ape_contacto': forms.TextInput(attrs={'class':'form-control'}),
			'correo_contacto': forms.TextInput(attrs={'class':'form-control'}),
			'fijo_contacto': forms.TextInput(attrs={'class':'form-control'}),
			'celu_contacto': forms.TextInput(attrs={'class':'form-control'}),
			'resum_problema': forms.TextInput(attrs={'class':'form-control'}),
			'asignado': forms.Select(attrs={'class':'form-control'}),
			'detall_problema': forms.Textarea(attrs={'class':'form-control'}),
			'estado': forms.Select(attrs={'class':'form-control'}),
		}

class EstablecimientoForm(forms.ModelForm):

	class Meta:
		model = Establecimiento
		fields = [
			'titulo',
		]
		labels = {
			'titulo':'Titulo',

		}
		widgets = {
			'titulo': forms.TextInput(attrs={'class':'form-control'}),

		}

class TemaForm(forms.ModelForm):

	class Meta:
		model = Tema
		fields = [
			'titulo',
		]
		labels = {
			'titulo':'Titulo',

		}
		widgets = {
			'titulo': forms.TextInput(attrs={'class':'form-control'}),

		}

class RespuestaForm(forms.ModelForm):

	class Meta:
		model = Respuestas
		fields = [
            'asunto' ,
            'mensaje' ,
		]
		labels = {
            'asunto': 'Asunto',
            'mensaje': 'Mensaje',
		}
		widgets = {
            'asunto': forms.TextInput(attrs={'class':'form-control'}),
            'mensaje': forms.Textarea(attrs={'class':'form-control'}),
		}

apps/ticket/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, request
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.contrib.auth.models import User
from apps.ticket.forms import TicketForm,EstablecimientoForm, TemaForm, RespuestaForm
from apps.ticket.models import Ticket, Establecimiento, Tema, Estado, Respuestas


# Create your views here.

def index(request):
    return render(request, 'ticket/index.html')

def ticket_view(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            print(obj.usuario)
            form.save()
        return redirect('ticket:ticket_list')
    else:
        form = TicketForm()
    return render(request, 'ticket/ticket_form.html', {'form': form})

def ticket_list(request):
    ticket = Ticket.objects.all().order_by('id')
    contexto = {'tickets': ticket}
    return render(request, 'ticket/ticket_list.html', contexto)

def ticket_edit(request, id_ticket):
    ticket = Ticket.objects.get(id=id_ticket)
    if request.method == "GET":
        form = TicketForm(instance=ticket)
    else:
        form = TicketForm(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
        return redirect('ticket:ticket_list')
    return render(request, 'ticket/ticket_form.html', {'form': form})

def ticket_delete(request, id_ticket):
    ticket = Ticket.objects.get(id=id_ticket)
    if request.method == 'POST':
        ticket_delete()
        return redirect('ticket:ticket_list')
    return render(request, 'ticket/ticket_delete.html', {'ticket': ticket})

class TicketList(ListView):
    model = Ticket
    tempalte_name = 'ticket/ticket_list.html'

class TicketCreate(CreateView):
    model = Ticket
    form_class = TicketForm
    tempalte_name = 'ticket/ticket_form.html'
    success_url = reverse_lazy('ticket:ticket_list')

class TicketUpdate(UpdateView):
    model = Ticket
    form_class = TicketForm
    tempalte_name = 'ticket/ticket_form.html'
    success_url = reverse_lazy('ticket:ticket_list')

class TicketDelete(DeleteView):
    model = Ticket
    success_url = reverse_lazy('ticket:ticket_list')

def TemaCreate(request, value):
    if value == 'tema':
        form = TemaForm(request.POST)
        data = {'value' : 'tema'}
    elif value == 'establecimiento':
        form = EstablecimientoForm(request.POST)
        data = {'value': 'establecimiento'}
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('ticket:ticket_form')
    else:
        form = TemaForm()
    return render(request, 'ticket/nuevo_form.html', {'form': form, 'data': data})

def EstadosView(request):
    total = Ticket.objects.filter().count()
    abierto = Ticket.objects.filter(estado_id=0).count()
    cerrado = Ticket.objects.filter(estado_id=1).count()
    pendiente = Ticket.objects.filter(estado_id=2).count()
    data = {
        'total':total,
        'abierto': abierto,
        'cerrado': cerrado,
        'pendiente': pendiente,
        }
    return render(request,"ticket/ticket_reportes.html", data)

def ticket_detalle(request, id_ticket):

    form = RespuestaForm()
    data = {
        'detalle': Ticket.objects.get(id=id_ticket),
        'resp': GetRespuestas(id_ticket),
        'form': form
    }
    ultimo = Respuestas.objects.latest('id')
    if request.method == 'POST':
        form = RespuestaForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user.first_name+' '+request.user.last_name
            obj.ticket = id_ticket
            print(request.user.first_name)
            if obj.asunto != ultimo.asunto or obj.mensaje != ultimo.mensaje :
                form.save()
        else:
            print(form.is_valid())
            print(form.errors)
    return render(request,"ticket/ticket_detalle.html", data)

def Cambiar_estado(request, id_ticket, id_estado):
    print(id_ticket+' - '+id_estado)
    ticket = Ticket.objects.get(id=id_ticket)
    estado = Estado.objects.get(id=id_estado)
    ticket.estado = estado
    print(estado)
    ticket.save()
    return redirect('ticket:ticket_list')

def GetRespuestas(id_ticket):
    resp = Respuestas.objects.filter(ticket=id_ticket).order_by('id')
    return resp

def SetRespuestas(id_ticket, asunto, mensaje, user):
        Respuestas.objects.create(usuario=user, asunto = asunto, mensaje = mensaje, ticket = id_ticket)

templates/ticket/create_form.html
{% extends 'base/base.html' %}
{% block title %} Crear Ticket {% endblock %}
{% block titulo %} Crear ticket {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            Por favor, complete el siguiente formulario para crear un nuevo Documento.
        </h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type='submit'>Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/ticket/nuevo_form.html
{% extends 'base/base.html' %}
{% block title %} Crear {{ data.value }}-ticket {% endblock %}
{% block titulo %} Crear {{ data.value }}-ticket {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            Por favor, complete el siguiente formulario para crear un nuevo {{ data.value }}.
        </h3>
        </div>		<div class="panel-body" class="form-control">
			<form method="POST">
			{% csrf_token %}
				<div class="row">
	    			<div class="col-lg-10" >
                        {{ form.as_p }}
                    </div>
					<div class="col-lg-2" align="right">
                        <br>
						<button class="btn btn-primary" type='submit'>Guardar</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/ticket/ticket_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
<div class="row">
    <div class="panel panel-default">
		<div class="panel-heading" align="center">
			<h3>
			Confirmar para eliminar un ticket.
		</h3>
		</div>
		<div class="panel-body" class="form-control">
			<form method="POST">
			{% csrf_token %}
				<div class="row">
	    			<div class="col-lg-6" >
						<h4>¿Desea eliminar el ticket N° {{ object.id }}?</h4>
					</div>
					<div class="col-lg-6" align="right"> 
						
								<button class="btn btn-danger" type="submit">Si, eliminar</button>
							
								<a class="btn btn-default" href="{% url 'ticket:ticket_list' %}"> Cancelar</a>
						
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/ticket/ticket_form.html
{% extends 'base/base.html' %}
{% block title %} Crear Ticket {% endblock %}
{% block titulo %} Crear ticket {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            Por favor, complete el siguiente formulario para crear un nuevo ticket.
        </h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Seleccione tema.</h4>
                        {% render_field form.tema %} 
                         <p align="right"><a href="{% url 'ticket:nuevo_form' 'tema' %}">Nuevo</a></p>
                    </div>
                    <div class="col-md-6 ">
                    <h4>Establecimiento de solicitud</h4>
                    {% render_field form.establecimiento %}
                    <p align="right"><a href="{% url 'ticket:nuevo_form' 'establecimiento'%}">Nuevo</a></p>
                        <br>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Informacion de contacto.</h4>
                        <br>
                         {% render_field form.nom_contacto autocomplete="on" placeholder="Nombre del concato" %}
                        <br>
                        {% render_field form.ape_contacto autocomplete="on" placeholder="Apellidos del concato" %}
                        <br>
                    </div>
                    <div class="col-lg-6"><br><br><br>

                        {% render_field form.correo_contacto placeholder="Correo del contacto" required=""> %}
                        <br>
                        <div class="row">
                            <div class="col-lg-6">
                                {% render_field form.fijo_contacto autocomplete="off" placeholder="Telefono fijo" %}
                            <br>
                            </div>
                            <div class="col-lg-6">
                                {% render_field form.celu_contacto autocomplete="off" placeholder="Telefono celular" required="off"  %}
                                <br>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                    <div class="row">
                            <div class="col-lg-6">
                        <h4>Datos del problema.</h4>
                                {% render_field form.resum_problema autocomplete="off"  placeholder="Resumen del problema" required=""> %}
                                <br>
                            </div>
                            <div class="col-lg-6">
                                <h4>Tecnico asignado.</h4>
                                 {% render_field form.asignado %}
                                 
                         <p align="right"><a href="{% url 'usuario:tecnico_form' %}">Nuevo</a></p>
                                <br>
                            </div>
                        </div>
                        <h4>Detalle del problema.</h4>
                        <br>
                     {% render_field form.detall_problema rows="3" id="imput2" style="margin: 0px -1px 0px 0px; height: 170px; width:max;" autocomplete="off" %}

                    <br>
                   
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <h4>Estado del ticket.</h4>
                        {{ form.estado }}
                    </div>
                    <div class="col-lg-6">
                    <div align="right">
                    <br><br>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a href="" class="btn btn-default" onclick="history.back();return false">Cancelar</a>
                    </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/ticket/ticket_list.html
{% extends 'base/base.html' %}
{% block titulo %} Listado{% endblock %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
	<div class="panel-heading">
		<h3>
		<i class="fa fa-list-ol fa-fw"></i> Listados de ticket ingresados.
	</h3>
	</div>
    <div class="panel-body">
    	<div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover dataTable" id="dataTables-example">
	            <thead>
	                <tr>
						<th>#</th>
						<th>Resumen</th>
						<th>Tema</th>
						<th>Establecimiento</th>
						<th>Solicitado</th>
						<th>asignado</th>
						<th>Creacion</th>
						<th style="width: 120px;">Estado</th>
						<th style="width: 120px;">Acciones</th>
					</tr>
	            </thead>
	            <tbody>

				{% if object_list %}
				{% for ticket in object_list %}

					<tr class="odd gradeX">

						<td> <a href="{% url 'ticket:ticket_detalle' ticket.id %}">{{ ticket.id }} </a></td>
						<td><a href="{% url 'ticket:ticket_detalle' ticket.id %}">{{ ticket.resum_problema }} </a></td>
						<td>{{ ticket.tema.titulo }}</td>
						<td>{{ ticket.establecimiento.titulo }}</td>
						<td>{{ ticket.nom_contacto }} {{ ticket.ape_contacto }}</td>
						<td>{{ ticket.asignado }}</td>
						<td>{{ ticket.fecha_creacion }}</td>
						<td>
							<div class="row" align="center">
							<div class="btn-group">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            {{ ticket.estado }}
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li><a class="btn" href="{% url 'ticket:estado_edit' ticket.id '0' %}"><i class="fa  fa-exclamation fa-fw"></i> Abierto</a>
                                            </li>
                                            <li><a class="btn" href="{% url 'ticket:estado_edit' ticket.id '1' %}"><i class="fa  fa-check fa-fw"></i> Cerrado</a>
                                            </li>
                                            <li><a class="btn" href="{% url 'ticket:estado_edit' ticket.id '2' %}"><i class="fa  fa-clock-o fa-fw"></i> Pendiente</a>
                                            </li>

                                        </ul>
                                    </div>
							</div>
						</td>
						<td>
							<div class="row" align="center">
							<div class="btn-group">
                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            Acciones
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            <li><a class="btn" href="{% url 'ticket:ticket_edit' ticket.id %}"><i class="fa  fa-print fa-fw"></i> Imprimir</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li><a class="btn" style="color: darkblue" href="{% url 'ticket:ticket_edit' ticket.id %}"><i class="fa  fa-edit fa-fw"></i> Editar</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li><a class="btn" style="color: darkred" href="{% url 'ticket:ticket_delete' ticket.id %}"><i class="fa  fa-times fa-fw"></i> Eliminar</a>
                                            </li>

                                            
                                        </ul>
                                    </div>
							</div>
						</td>
					</tr>
					{% endfor %}
					{% else %}
					<h1>No hay registro</h1>
					{% endif %}
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

{% endblock %}

templates/ticket/ticket_reportes.html
{% extends 'base/base.html' %}
{% block title %} Estados de Ticket {% endblock %}
{% block titulo %} Estados de ticket {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            Este es el estado actual de los ticket ingresados.
        </h3>
        </div>
        <div class="row panel-body">
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-list-alt fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ total }}</div>
                                <div>Todos los ticket</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'ticket:ticket_list' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalles</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-green">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa  fa-clock-o fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ pendiente }}</div>
                                <div>Total ticket pendientes</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'ticket:ticket_list_pendiente' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalles</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-yellow">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-check fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ cerrado }}</div>
                                <div>Total ticket resueltos</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'ticket:ticket_list_cerrado' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalles</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-red">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-exclamation fa-5x"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div class="huge">{{ abierto }}</div>
                                <div>Total ticket pendientes!</div>
                            </div>
                        </div>
                    </div>
                    <a href="{% url 'ticket:ticket_list_abierto' %}">
                        <div class="panel-footer">
                            <span class="pull-left">Ver detalles</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}