apps/document/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required


from apps.document.views import Document_create, Detalle_doc, Create_value, Active_off, Documento_list, Documento_edit, Edit_value, \
    DocumentoCreate

urlpatterns = [
    url(r'^$', login_required(Document_create), name='document_form'),
    url(r'^nuevo$', login_required(Document_create), name='document_form'),
    url(r'^nuevo/(?P<value>\w+)$', login_required(Create_value), name='create_value'),
    url(r'^editar/(?P<value>\w+)/(?P<id_value>\d+)$', login_required(Edit_value), name='edit_value'),
    url(r'^active_off/(?P<value>\w+)/(?P<id_value>\d+)$', login_required(Active_off), name='active_off'),
    url(r'^list/$', login_required(Documento_list), name="documento_list"),
    url(r'^detalle/(?P<id_docum>\d+)$',login_required(Detalle_doc), name="documento_detalle"),
    url(r'^editar/(?P<id_documento>\d+)$',login_required(Documento_edit), name="documento_edit"),
    ]

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf import settings
from django.conf.urls.static import static
#from apps.home.views import home
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO: mejorar orden en urls
urlpatterns += [
    url(r'^', include('apps.document.urls', namespace='document')),
    url(r'^archivos/', include('apps.archivos.urls', namespace='archivos')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^accounts/login/', login, {'template_name':'registration/login.html'}, name='login'),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuario')),
    url(r'^documentos/', include('apps.document.urls', namespace='document')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/document/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#python3 manage.py makemigrations
#python3 manage.py migrate

class Desde(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	cargo = models.CharField(max_length=100)
	activo = models.BooleanField(default=True)
	firma = models.TextField()
	def __str__(self):
		return '{}'.format(self.nombre+" "+self.apellidos)

class Para(models.Model):
	nombre = models.CharField(max_length=50)
	apellidos = models.CharField(max_length=50)
	cargo = models.CharField(max_length=100)
	activo = models.BooleanField(default=True)
	def __str__(self):
		return '{}'.format(self.nombre+" "+self.apellidos)

class Tipo_docum(models.Model):
	titulo = models.CharField(max_length=50)
	def __str__(self):
		return '{}'.format(self.titulo)

class Documento(models.Model):
	tipo= models.ForeignKey(Tipo_docum, null=False, blank=True, on_delete=models.CASCADE)
	num = models.IntegerField(null=False)
	ant = models.CharField(max_length=50, null=True)
	mat = models.CharField(max_length=50, null=False)
	desde = models.ForeignKey(Desde, null=False, blank=True, on_delete=models.CASCADE)
	para = models.ForeignKey(Para, null=False, blank=True, on_delete=models.CASCADE)
	cuerpo = models.TextField(null=False)
	piepag = models.TextField(null=False)
	creacion = models.TextField()
	ano =  models.TextField()
	usuario =  models.TextField()
	activo = models.BooleanField(default=True)

class Alertmessage(models.Model):
	tipo = models.CharField(max_length=50, null=True)
	message = models.CharField(max_length=50, null=True)
	dueno = models.IntegerField(null=True)
	def __str__(self):
		return '{}'.format(self.message)

apps/document/forms.py
from django import forms
from apps.document.models import Documento, Desde, Para

class DocumentoForm(forms.ModelForm):

	class Meta:
		model=Documento
		fields=[
			'tipo',
            'ant',
			'mat',
			'desde',
			'para',
			'cuerpo',
			'piepag',
		]
		labels={
			'tipo':'Tipo',
            'ant':'Ant',
			'mat':'Mat',
			'desde':'Desde',
			'para':'Para',
			'cuerpo':'Cuerpo',
			'piepag':'Piepag',
		}
		widgets={
			'tipo':forms.Select(attrs={'class':'form-control'}),
			'ant':forms.Select(attrs={'class':'form-control'}),
			'mat': forms.TextInput(attrs={'class':'form-control'}),
			'desde': forms.Select(attrs={'class':'form-control'}),
			'para': forms.Select(attrs={'class':'form-control'}),
			'cuerpo': forms.Textarea(attrs={'class':'form-control'}),
			'piepag': forms.Textarea(attrs={'class':'form-control'}),
			}

class DesdeForm(forms.ModelForm):

	class Meta:
		model = Desde
		fields = [
			'nombre',
			'apellidos',
			'cargo',
			'firma'
		]
		labels = {
			'nombre':'Nombre',
			'apellidos':'Apellidos',
			'cargo':'Cargo',
			'firma': 'Firma',

		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'cargo': forms.TextInput(attrs={'class':'form-control'}),
			'firma': forms.Textarea(attrs={'class':'form-control'}),

		}


class ParaForm(forms.ModelForm):

	class Meta:
		model = Para
		fields = [
			'nombre',
			'apellidos',
			'cargo',
		]
		labels = {
			'nombre':'Nombre',
			'apellidos':'Apellidos',
			'cargo':'Cargo',

		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'apellidos': forms.TextInput(attrs={'class':'form-control'}),
			'cargo': forms.TextInput(attrs={'class':'form-control'}),

		}

apps/document/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.document.models import Documento, Para, Desde, Tipo_docum, Alertmessage
from apps.document.forms import DocumentoForm, DesdeForm, ParaForm
import datetime, time

# Create your views here.

class DocumentoCreate(CreateView):
    model = Documento
    data = {'value' :'documento'}
    form_class = DocumentoForm
    tempalte_name = 'ticket/ticket_form.html'
    success_url = reverse_lazy('document:document_form')

def Fecha_actual():
    x = datetime.datetime.now()
    y = time.strftime("%A")

    def sw_dia(x):
        return {
            'Monday': 'Lunes',
            'Tuesday': 'Martes',
            'Wednesday': 'Miercoles',
            'Thursday': 'Jueves',
            'Friday': 'Viernes',
            'Saturday': 'Sabado',
            'Sunday': 'Domingo',
        }[x]

    def sw_mes(x):
        return {
            1: 'Enero',
            2: 'Febrero',
            3: 'Marzo',
            4: 'Abril',
            5: 'Mayo',
            6: 'Junio',
            7: 'Julio',
            8: 'Agosto',
            9: 'Septiembre',
            10: 'Octubre',
            11: 'Noviembre',
            12: 'Diciembre',
        }[x]

    fecha = {
        'ndia': sw_dia(y),
        'dia': x.day,
        'mes': sw_mes(x.month),
        'ano': x.year
    }
    return fecha

def Document_create(request):
    try:
        doc_ant = Documento.objects.latest('id')
        val = True
    except Documento.DoesNotExist:
        doc_ant = {
            'num': 0,
            'piepag': '',
        }
        val = False
    fecha = Fecha_actual()
    fecha_str = fecha['ndia']+", "+str(fecha['dia']) + " de " + fecha['mes'] + " del " + str(fecha['ano'])
    if val:
        data = {
            'pie_anterior': doc_ant.piepag,
            'num': doc_ant.num,  # cambiar por el siguiente numeromde la base de datos
        }
    else:
        data = {
            'pie_anterior': '',
            'num': doc_ant['num']  # cambiar por el siguiente numeromde la base de datos
        }
    if request.method == 'POST':
        form = DocumentoForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.usuario = request.user
            tipo_ant = Documento.objects.filter(tipo=obj.tipo)
            doc_ant=tipo_ant.last()
            if val and doc_ant.ano == str(fecha['ano']):
                obj.num = int(doc_ant.num) + 1
            else:
                obj.num = 1
            obj.creacion = fecha_str
            obj.ano = fecha['ano']
            valdos = 0
            if obj.desde != doc_ant.desde:
                valdos = valdos + 1
            if obj.para != doc_ant.para:
                valdos = valdos + 1
            if obj.cuerpo != doc_ant.cuerpo:
                valdos = valdos + 1
            if obj.mat != doc_ant.mat:
                valdos = valdos + 1


            if valdos < 2:
                Documento.objects.filter(id=doc_ant.id).update(num = doc_ant.num,
                                                               mat = obj.mat,
                                                               desde = obj.desde,
                                                               para = obj.para,
                                                               cuerpo = obj.cuerpo,
                                                               piepag = obj.piepag)


                obj.id = doc_ant.id

                setMessage('estandar', 'Se ha modificado el documento.', obj.id)
            else:
                form.save()
            return redirect('document:documento_detalle', obj.id)
        else:
            print(form.is_valid())
            print(form.errors)
            form = DocumentoForm(request.POST)

    else:
        form = DocumentoForm()



    data['ant'] = Documento.objects.all().order_by('-id')[:20]
    data['desde'] = Desde.objects.filter(activo=True).order_by('id')
    data['para'] = Para.objects.filter(activo=True).order_by('id')
    data['tipo'] = Tipo_docum.objects.all().order_by('id')

    return render(request, 'document/documento_form.html', dict(form=form, fecha=fecha, data=data))

def Create_value(request, value):
    if value == 'desde':
        data = {'titulo': 'Remitente',
                'tema': 'remitente',
                'value': value}
        model = Desde.objects.all().order_by('nombre')
        form= DesdeForm()
        if request.method == 'POST':
            form = DesdeForm(request.POST)
            if form.is_valid():
                form.save()
            return redirect('document:create_value', value)
    elif value == 'para':
        data={'titulo' :'Destinatario',
              'tema' : 'destinatario',
                'value': value}
        model = Para.objects.all().order_by('nombre')
        form= ParaForm()
        if request.method == 'POST':
            form = ParaForm(request.POST)
            if form.is_valid():
                form.save()
            return redirect('document:create_value', value)

    return render(request, 'document/create_value.html', {'form' :form, 'model': model, 'data': data})

def Edit_value(request, value, id_value):
    if value == 'desde':
        data = {'titulo': 'Remitente',
                'tema': 'remitente',
                'value': value}
        model = Desde.objects.all().order_by('nombre')
        modelform = Desde.objects.get(id = id_value)
        if request.method == 'GET':
            form = DesdeForm(instance=modelform)
        else:
            form = DesdeForm(request.POST, instance=modelform)
            if form.is_valid():
                form.save()
            return redirect('document:create_value', value)

    elif value == 'para':
        data={'titulo' :'Destinatario',
              'tema' : 'destinatario',
                'value': value}
        model = Para.objects.all().order_by('nombre')
        modelform = Para.objects.get(id=id_value)
        if request.method == 'GET':
            form = DesdeForm(instance=modelform)
        else:
            form = ParaForm(request.POST, instance=modelform)
            if form.is_valid():
                form.save()
            return redirect('document:create_value', value)

    return render(request, 'document/create_value.html', {'form' :form, 'model': model, 'data': data, 'modelform': modelform})

def Active_off(request, value, id_value):
    if value == 'desde':
        value_ = Desde.objects.get(id=id_value)
        value_.activo = False
        value_.save()
        return redirect('document:create_value', value)
    elif value == 'para':
        value_ = Para.objects.get(id=id_value)
        value_.activo = False
        value_.save()
        return redirect('document:create_value', value)
    elif value == 'documento':
        value_ = Documento.objects.get(id=id_value)
        value_.activo = False
        value_.save()
        return redirect('document:documento_list')

def Documento_edit(request, id_documento):
    model = Documento.objects.get(id=id_documento)
    data={'pie_anterior': model.piepag,
          'cuerpo': model.cuerpo}
    if request.method == "GET":
        form = DocumentoForm(instance=model)
    else:
        form = DocumentoForm(request.POST, instance=model)
        if form.is_valid():
            obj = form.save(commit=False)
            _obj=Documento.objects.get(num = obj.num, tipo = obj.tipo)
            form.save()

            setMessage('estandar', 'Se ha modificado el documento.', _obj.id)
            return redirect('document:documento_detalle', _obj.id)
    fecha = Fecha_actual()
    data['ant'] = Documento.objects.all().order_by('-id')[:20]
    data['desde'] = Desde.objects.filter(activo=True).order_by('id')
    data['para'] = Para.objects.filter(activo=True).order_by('id')
    data['tipo'] = Tipo_docum.objects.all().order_by('id')
    return render(request, 'document/documento_form.html', {'form': form,'data': data, 'fecha': fecha})

def Documento_list(request):
    model = Documento.objects.all().order_by('-id')
    return render(request, 'document/documento_list.html', {'model': model})

def Detalle_doc(request, id_docum):
    model = Documento.objects.get(id=id_docum)
    msj = getMessage('estandar')
    mensaje = 'null'
    if msj.message !="null" and msj.dueno == model.id:
        mensaje = getMessage('estandar').message
        setMessage('estandar','null',model.id )

    data = {
        'detalle': model,
        'alert': mensaje
    }

    return render(request, "document/detalle_documento.html", data)

def getMessage(tipo):
      return Alertmessage.objects.get(tipo=tipo)

def setMessage(tipo, msj, id):
      obj = Alertmessage.objects.get(tipo=tipo)
      obj.message = msj
      obj.dueno = id
      obj.save()

templates/document/create_value.html
{% extends 'base/base.html' %}
{% block title %} Crear {{ data.titulo }} {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            <i class="fa fa-plus fa-fw"></i> Por favor, complete el siguiente formulario para crear un nuevo {{ data.tema }}.
        </h3>
        </div>
        <div class="panel-body">
            <form method="post">
                <div class="row">
                         {% csrf_token %}

                        <div class="col-lg-3">
                            {{ form.nombre|safe }} <br>
                        </div>
                        <div class="col-lg-3">
                            {{ form.apellidos|safe }} <br>
                        </div>
                        <div class="col-lg-6">
                            {{ form.cargo|safe }} <br>
                        </div>

                </div>
                <div class="row">
                    <div class="col-lg-9">
                        {% if data.value == 'desde' %}
                         <textarea class="form-control" name="firma" placeholder="Firma" cols="33" rows="2" >{{ modelform.firma|safe }}</textarea>
                            <br>
                        {% endif %}
                    </div>
                    <div class="col-lg-3" style="">
                        <input type="submit" style="width: 100%" class="btn btn-primary" value="Guardar" ><br>
                    </div>

            </form>

        </div>
    </div>

</div>
    <div class="row">
    <div class="panel panel-default">
	<div class="panel-heading">
		<h3>
		<i class="fa fa-users fa-fw"></i> Listados de {{ data.tema }}s registrados.
	</h3>
	</div>
    <div class="panel-body">
    	<div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover dataTable" id="dataTables-example">
	            <thead>
	                <tr>

						<th>Nombre</th>
						<th>Apellidos</th>
						<th>Cargo</th>
						<th style="width: 120px;">Acciones</th>
					</tr>
	            </thead>
	            <tbody>


				{% for models in model %}
                        {% if models.activo == True %}
                            <tr class="odd gradeX" >

                                <td>{{ models.nombre }}</td>
                                <td>{{ models.apellidos }}</td>
                                <td>{{ models.cargo }}</td>
                                <td>
                                    <div class="row" align="center">
                                    <div class="btn-group">
                                                <a type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                                    Acciones
                                                    <span class="caret"></span>
                                                </a>
                                                <ul class="dropdown-menu pull-right" role="menu">
                                                    <li><a class="btn" href="{% url 'document:edit_value' data.value models.id %}" style="color: darkblue" >Editar</a>
                                                    </li>
                                                    <li><a class="btn" href="{% url 'document:active_off' data.value models.id %}" style="color: darkred" >Eliminar</a>
                                                    </li>
                                                </ul>
                                            </div>

                                    </div>
                                </td>
                            </tr>
                        {% endif  %}
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

{% endblock %}

templates/document/detalle_documento.html
{% extends 'base/base.html' %}
{% block title %} Detalle de documento N°{{ detalle.num }} {% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<div >
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-lg-8">
                    <h3><i class="fa fa-file-text fa-fw"></i> Documento N°  {{ detalle.ano }}/{{ detalle.num }} </h3>
                </div>
                <div class="col-lg-4" align="right">
                    <div class="btn-group" style="margin-top: 4%">
                        <a class="btn btn-default" href="{% url 'document:documento_edit' detalle.id %}"><i class="fa fa-edit"></i> Editar</a>

                    </div>
                    <div class="btn-group" style="margin-top: 4%">
                        <button id="print_btn" class="btn btn-primary"><i class="fa fa-print"></i> Imprimir</button>
                    </div>
                </div>
            </div>
        </div>
    {% if alert != 'null' %}
        <div class="alert alert-danger alert-dismissable ">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            {{ alert }} <!-- <a href="#" class="alert-link">Alert Link</a>. -->
        </div>
    {% endif %}
        <div  align="center" class="hidden-xs">
            <style type="text/css">
                .papel {

                    -webkit-box-shadow: 00px 0px 50px #888;
                    -moz-box-shadow: 0px 0px 50px #888;
                    box-shadow: 0px 0px 50px #888;
                    width: 768px;
                    height: 1200px;
                    padding-top: 30px;
                    padding-bottom: 30px;
                    margin-bottom: 60px;
                }
            </style>
            <div id="documento"  style="padding-top: 30px; padding-left: 50px; padding-right:50px; font-family: Arial, sans-serif;">
                <style type="text/css">
                    .doc__ {
                        font-family: Arial, sans-serif;
                        text-align: left;
                        margin-left: 9%;
                        margin-right: 9%;
                        width: 590px;
                        height: 1100px;
                        margin-top: 0%;
                        font-size: 12pt;
                        font-weight: bold;
                    }
                    .cuerpo_oficio {
                        /*text-indent: 140px; */
                        text-align: justify;
                        min-height: 380px;
                        width: auto;
                        margin-top:5px;
                        font-size: 12pt;
                        line-height: 1.3;
                    }
                    .cuerpo_carta {
                        /*text-indent: 140px; */
                        text-align: justify;
                        min-height: 200px;
                        width: auto;
                        margin-top:5px;
                        font-size: 12pt;
                        line-height: 1.3;
                    }
                /*    div { border: red 1px solid; } */
                    table, td, tr {
                 /*       border: blue 1px solid; */
                        font-weight: bold;
                    }
                     @page
                    {
                        size: auto;
                        margin: 0mm;
                    }
                </style>
                <div class="papel">
                    <div class="doc__ ">
                        <br>
                        <div >
                            <div style="float: left;vertical-align: top">
                                <img src="/media/img/logo.png" alt="logo" width="170px" height="auto"><br>

                            </div>
                            <div style="text-align: left; margin-left: 50%;padding-top: 100px">

                                <p>ORD.: N°{{ detalle.num }}/{{ detalle.ano }}<br>
                                ANT.: {{ detalle.ant.title }}<br>
                                MAT.: {{ detalle.mat }}.<br></p>

                            </div>
                        </div>
                        <div style="padding-top: 20px; padding-bottom: 50px">Colina, {{ detalle.creacion }}.-</div>
                        <table>
                            <tr style="vertical-align: top">
                                <td width="50" height="100 ">A</td>
                                <td width="50" height="100 ">:</td>
                              <td width="475">{{ detalle.para.nombre }} {{ detalle.para.apellidos }}<br>{{ detalle.para.cargo }}</td>
                            </tr>
                            <tr style="vertical-align: top">
                              <td width="50" height="100"  >DE</td>
                              <td width="50" height="100"  >:</td>
                              <td width="475">{{ detalle.desde.nombre }} {{ detalle.desde.apellidos }}<br>{{ detalle.desde.cargo }}</td>
                            </tr>
                        </table>
                        {% if detalle.tipo.titulo == "Memorando" %}
                            <div class="cuerpo_carta">
                                <p style="font-weight: normal"> {{ detalle.cuerpo|linebreaksbr }}</p>
                            </div>
                        {% else %}
                            <div class="cuerpo_oficio">
                                <p style=" font-weight: normal"> {{ detalle.cuerpo|linebreaksbr }}</p>
                            </div>
                        {% endif %}
                        <div style="float: left; font-weight: normal; "><br><br><br><br><br><br><br>
                           {{ detalle.piepag|linebreaksbr }}
                        </div>
                        <div style="margin-left: 30%; text-align: center; width: 350px">
                           {{ detalle.desde.firma|linebreaksbr }}
                        </div>
                        <br><br><br>
                    </div>
                </div>
            </div>
            <div align="right">**Correlativo interno {{ detalle.id }}</div>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        $('#print_btn').click(function () {
          $('#documento').printThis({});
        });
      });
</script>
{% endblock %}

templates/document/documento.html
{% extends 'base/base.html' %}
{% block title %} Crear Ticket {% endblock %}
{% block titulo %} Crear ticket {% endblock %}
{% load widget_tweaks %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>
            Documento
        </h3>
        </div>
        <div class="panel-body">
            
        </div>
    </div>
</div>
{% endblock %}

templates/document/documento_list.html
{% extends 'base/base.html' %}
{% block title %} Listado de documentos{% endblock %}
{% block content %}
<div class="row">
    <div class="panel panel-default">
	<div class="panel-heading">
		<h3>
		Listados de documentos.
	</h3>
	</div>
    <div class="panel-body hidden-xs hidden-md">
    	<div class="dataTable_wrapper">
            <table class="table table-striped table-hover dataTable" id="dataTables-example">
	            <thead>
	                <tr>
						<th>#</th>
						<th>Materia</th>
						<th>Fecha</th>
						<th>Tipo</th>
						<th>Remitente</th>
						<th>Destinatario</th>
						<th style="width: 120px;">Acciones</th>
					</tr>
	            </thead>
	            <tbody>

				{% for documentos in model %}
                    {% if documentos.activo %}
					<tr class="odd gradeX" >
						<td >{{ documentos.num }}/{{ documentos.ano }}</td>
						<td> <a href="{% url 'document:documento_detalle' documentos.id %}"> <B>{{ documentos.mat }}</B></a></td>
						<td>{{ documentos.creacion }}</td>
						<td>{{ documentos.tipo }}</td>
						<td>{{ documentos.desde.nombre }} {{ documentos.desde.apellidos }}</td>
						<td>{{ documentos.para.nombre }} {{ documentos.para.apellidos }}</td>
						<td>
							<div class="row" align="center">
							<div class="btn-group">
                                        <a type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                            Acciones
                                            <span class="caret"></span>
                                        </a>
                                        <ul class="dropdown-menu pull-right" role="menu">
                                            </li>
                                            <li><a class="btn" href="{% url 'document:documento_detalle' documentos.id %}">Imprimir</a>
                                            </li>
                                            <li><a class="btn" href="{% url 'document:documento_edit' documentos.id %}">Editar</a>
                                            </li>
                                            <li class="divider"></li>
                                            <li><a class="btn " style="color: darkred" href="{% url 'document:active_off' 'documento' documentos.id %}"> Anular</a>
                                            </li>


                                        </ul>
                                    </div>

							</div>
						</td>
					</tr>
                    {% else %}

					<tr class="odd gradeX" style="color: #737373;">

						<td>{{ documentos.num }}/{{ documentos.ano }}</td>
						<td> <B>{{ documentos.mat }}</B></td>
						<td>{{ documentos.creacion }}</td>
						<td>{{ documentos.tipo }}</td>
						<td>{{ documentos.desde.nombre }} {{ documentos.desde.apellidos }}</td>
						<td>{{ documentos.para.nombre }} {{ documentos.para.apellidos }}</td>
                        <td align="center"> <a type="button" disabled="" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="color: #737373;" aria-expanded="false">Nulo</a></td>
					</tr>
                    {% endif %}
					{% endfor %}

				</tbody>
			</table>
		</div>
	</div>
</div>
</div>

{% endblock %}

templates/document/pdf.html
{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Helvetica", "sans-serif";
            color: #333333;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="main">
            <h1>Hi there!</h1>
            <img src="file:///STATIC_ROOT/img/logo.png" />
        </div>
    </div>
{% endblock %}