apps/cambios/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


from apps.cambios.views import CambiosView

urlpatterns = [
    url(r'^$', login_required(CambiosView), name='index'),
    ]

proyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from django.conf import settings
from django.conf.urls.static import static
#from apps.home.views import home
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO: mejorar orden en urls
urlpatterns += [
    url(r'^', include('apps.document.urls', namespace='document')),
    url(r'^archivos/', include('apps.archivos.urls', namespace='archivos')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^accounts/login/', login, {'template_name':'registration/login.html'}, name='login'),
    url(r'^ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuario')),
    url(r'^documentos/', include('apps.document.urls', namespace='document')),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/cambios/models.py
from django.db import models

# Create your models here.

class Cambio(models.Model):
    detalle = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '{}'.format(self.detalle)

apps/cambios/forms.py
from django import forms
from apps.cambios.models import Cambio


class CambioForm(forms.ModelForm):

	class Meta:
		model = Cambio
		fields = [
			'detalle',
		]
		labels = {
			'detalle':'Detalle',
		}
		widgets = {
			'detalle': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/cambios/views.py
from django.shortcuts import render
from apps.cambios.models import Cambio
from apps.cambios.forms import CambioForm

# Create your views here.
def CambiosView(request):
    data = {'model': Cambio.objects.all(),
            'form': CambioForm(),
            'ultimo':Cambio.objects.last()}
    if request.method == 'POST':
        form = CambioForm(request.POST)
        if form.is_valid():
            data['val']=True
            form.save()
    return render(request, 'cambios/index.html', data)

templates/cambios/index.html
{% extends 'base/base.html' %}
{% block title %} Cambios registrados {% endblock %}
{% block head %}
{% endblock %}
{% block content %}
   <div class="row">
    <div class="panel panel-default">
	<div class="panel-heading">
		<h3>
		Listados de documentos.
	</h3>
	</div>
    {% if user.get_username == 'admin' %}
    <div class="row container">
            <form method="POST">

			{% csrf_token %}
	    			<div class="col-lg-9" >
                        <br>
                        {% if val %}

                            <input type="text" name="detalle" id="id_detalle" value="{{ ultimo }}" required class="form-control" placeholder="Ingresar detalle"/>
                        {% else %}
                            <input type="text" name="detalle" id="id_detalle" value="" required class="form-control" placeholder="Ingresar detalle"/>
                        {% endif %}
                    </div>
					<div class="col-lg-2" align="right">
                        <br>
						<button class="btn btn-primary" type='submit'>Guardar</button>
					</div>
			</form>

    </div>
    {% endif %}
    <div class="panel-body hidden-xs hidden-md">
    	<div class="dataTable_wrapper">
            <table class="table table-striped table-hover dataTable" id="dataTables-example">
	            <thead>
	                <tr>
						<th>#</th>
						<th style="min-width: 220px">Fecha</th>
						<th>Detalle</th>
					</tr>
	            </thead>
	            <tbody>

				{% for cambio in model %}
					<tr class="odd gradeX" >
						<td >{{ cambio.id }}</td>
						<td>{{ cambio.updated_at }}</td>
						<td>{{ cambio.detalle }}</td>
					</tr>
                {% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
</div>
{% endblock %}